### ISSUE TITLE
Sourcing fails with certain characters

### ISSUE THREAD

**Issue by peteruithoven** [AndersDJohnson/dotenv-export#2]
When I have a `.env` file with values containing a "`" it can't be sourced. 

Example `.env` file: 
``` env
DB_PASS="some`password"
```
Gives the following result:
```
$ source <(dotenv-export)
bash: /dev/fd/63: line 1: unexpected EOF while looking for matching ``'
bash: /dev/fd/63: line 2: syntax error: unexpected end of file
```

It can be sourced when I escape it by adding a `\` in front of it:
```
DB_PASS="some\`password"
```
But then my regular Node.js code will fail. What would be a good solution here?

**Comment by AndersDJohnson** [comment]
@peteruithoven I suppose this is best described as a bug in the Node version of`dotenv` itself? I feel like it should support escapes.

But as a stop-gap, I've added a feature to automatically escape backticks, and other special characters like `$`, `{`, and `}`. I don't think people will need those when using Node `dotenv`, since they're mainly meant for evaluating commands within shell scripts, which Node `dotenv` doesn't support.

**Comment by peteruithoven** [comment]
Thanks!

**Comment by AndersDJohnson** [comment]
@peteruithoven No worries. Please star!
